### ISSUE TITLE
Uncaught (in promise) DOMException: No Services found in device.

### ISSUE THREAD

**Issue by thangta** [urish/web-bluetooth-polyfill#50]
Hi, 
I got an error when run Mesh proxy example from Bluetooth SIG. 
  
Uncaught (in promise) DOMException: No Services found in device.
Please see image below
![image](https://user-images.githubusercontent.com/13417944/44379384-e04d2c00-a52f-11e8-9fdd-e3eafa43b955.png)

**Comment by urish** [comment]
Thanks for reporting the issue.

By looking at the screen shot, it seems like you are not using the polyfill, rather the native Chrome implementation that is now available in Chrome Canari. You can open a bug for Chrome at http://crbug.com/new .

Anyway, this polyfill is now deprecated since the Web Bluetooth API for Windows is now implemented by Chrome Canary. I won't be fixing any issues in it.

**Comment by thangta** [comment]
Hi, I still get same error in Chrome Canary. He is the screen short and debug log 
[pdfhjjeijpigdmfdchmkjllglhmppnkl-1534837281579. log](https://github.com/urish/web-bluetooth-polyfill/files/2305291/pdfhjjeijpigdmfdchmkjllglhmppnkl-1534837281579.log)


![image](https://user-images.githubusercontent.com/13417944/44387796-ad676000-a550-11e8-836d-881a3f7d5f98.png)
